"""empty message

Revision ID: 2de54d025014
Revises: cf2d9fd005ca
Create Date: 2023-07-04 14:35:29.291577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import app

# revision identifiers, used by Alembic.
revision = '2de54d025014'
down_revision = 'cf2d9fd005ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('username', sa.VARCHAR(length=52), nullable=False),
    sa.Column('salty_password', app.datatypes.SaltyVarChar(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('blog_user_data', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('blog_user_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_user_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=52), nullable=False),
    sa.Column('salty_password', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('blog_user_data', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    op.drop_table('userdata')
    # ### end Alembic commands ###
