"""empty message

Revision ID: 37d9b2faa832
Revises: 2464f298d76d
Create Date: 2023-08-06 12:02:53.025298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d9b2faa832'
down_revision = '2464f298d76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['userdata.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['userdata.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
