"""ezier naming

Revision ID: c9176b2ced75
Revises: 37d9b2faa832
Create Date: 2023-08-06 22:07:55.457890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9176b2ced75'
down_revision = '37d9b2faa832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands automate generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands automate generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdata', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
