"""adding bloguserdata

Revision ID: cf2d9fd005ca
Revises: 
Create Date: 2023-07-04 14:02:20.612881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import app

# revision identifiers, used by Alembic.
revision = 'cf2d9fd005ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blog_user_data',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.VARCHAR(length=64), nullable=False),
        sa.Column('username', sa.VARCHAR(length=52), nullable=False),
        sa.Column('salty_password', app.datatypes.SaltyVarChar(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('userdata', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('userdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'userdata',
        sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
        sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
        sa.Column('pwd', mysql.CHAR(length=64), nullable=False),
        sa.Column('salt', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('create_date', mysql.DATETIME(), nullable=False),
        sa.Column('recent_login', mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('email'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    with op.batch_alter_table('userdata', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    op.drop_table('blog_user_data')
    # ### end Alembic commands ###
